<?php
/**
 * Juridische pagina's — algemene voorwaarden en klachtenprocedure, verbatim
 * overgenomen van react2u.nl (binnengehaald 2026-08-23). Dit is een juridisch
 * document: NIET parafraseren, NIET aanvullen. De privacyverklaring van de
 * huidige site toont bij vergissing de verkeerde pagina-inhoud (het
 * Begeleiding & Coaching-blok) en is daarom geen bruikbare bron — die pagina
 * blijft [PLACEHOLDER] tot de klant de echte tekst aanlevert.
 *
 * Meegenomen in deploy/inhoud-react2u.php.
 *
 * @package React2u
 */

if ( ! defined( 'WP_CLI' ) || ! WP_CLI ) {
	exit( "Dit bestand hoort alleen via inhoud-react2u.php te draaien.\n" );
}

function react2u_inhoud_juridisch(): array {
	return array(
		'algemene-voorwaarden' => array(
			'titel'   => 'Algemene voorwaarden',
			'excerpt' => 'De algemene voorwaarden van React2u B.V., van toepassing op het basiscontract en op alle offertes, aanbiedingen en overeenkomsten.',
			'body'    =>
	react2u_inhoud_p( 'React2u is een besloten vennootschap met beperkte aansprakelijkheid: React2u B.V. Statutair gevestigd te Alkmaar, ingeschreven bij de Kamer van Koophandel van Eindhoven onder nummer 90015258, alsmede werknemers van React2u B.V.' ) . "\n"
				. react2u_inhoud_h2( 'Begripsbepalingen' ) . "\n"
				. react2u_inhoud_h3( 'Diensten en adviezen' ) . "\n"
				. react2u_inhoud_p( 'Alle diensten en adviezen die door React2u in opdracht van een opdrachtgever ten behoeve van die opdrachtgever of een door hem aangewezen derde worden verricht.' ) . "\n"
				. react2u_inhoud_h3( 'Opdrachtgever' ) . "\n"
				. react2u_inhoud_p( 'De natuurlijke persoon, dan wel de rechtspersoon, waarmee React2u onderhandelt over het sluiten van een overeenkomst, dan wel waarmee React2u een overeenkomst heeft gesloten.' ) . "\n"
				. react2u_inhoud_h3( 'Partijen' ) . "\n"
				. react2u_inhoud_p( 'React2u en opdrachtgever gezamenlijk.' ) . "\n"
				. react2u_inhoud_h3( 'Basiscontract' ) . "\n"
				. react2u_inhoud_p( 'Het contract waarin de basisafspraken voor arbodienstverlening zijn vastgelegd, waarmee opdrachtgever voldoet aan de wettelijke eisen voor aansluiting bij een arbodienstverlening.' ) . "\n"
				. react2u_inhoud_h3( 'Overeenkomst' ) . "\n"
				. react2u_inhoud_p( 'De overeenkomst tussen React2u en opdrachtgever ter zake het verrichten van diensten en het geven van adviezen. De overeenkomst komt tot stand door het geven van opdracht middels een ziekmelding en daarbij een keuze te maken voor ofwel een verrichting ofwel een akkoord op een offerte telefonisch of per e-mail.' ) . "\n"
				. react2u_inhoud_h2( 'A. Toepasselijkheid' ) . "\n"
				. react2u_inhoud_p( 'Deze algemene voorwaarden zijn van toepassing op het basiscontract en op alle offertes, aanbiedingen en overeenkomsten van React2u en op alle daaruit voortvloeiende verbintenissen en (rechts)handelingen.' ) . "\n"
				. react2u_inhoud_p( 'Afwijkingen van deze algemene voorwaarden zijn eerst geldig na uitdrukkelijke schriftelijke bevestiging door React2u. In geval van één of meer bepalingen van deze algemene voorwaarden wordt afgeweken, blijven de overige bepalingen onverkort van toepassing.' ) . "\n"
				. react2u_inhoud_p( 'Deze algemene voorwaarden zijn tevens van toepassing ten behoeve van door React2u bij de uitvoering van de overeenkomst ingeschakelde derden. Deze derden kunnen in hun relatie tot de opdrachtgever rechtstreeks een beroep doen op deze algemene voorwaarden tenzij zij hun eigen algemene voorwaarden zijn overeengekomen.' ) . "\n"
				. react2u_inhoud_p( 'De toepasselijkheid van eventuele inkoop- of andere voorwaarden van opdrachtgever wordt uitdrukkelijk van de hand gewezen.' ) . "\n"
				. react2u_inhoud_p( 'Indien één of meerdere bepalingen in deze algemene voorwaarden nietig zijn of vernietigd mochten worden, blijven de overige bepalingen van toepassing. React2u en opdrachtgever zullen alsdan in overleg treden om nieuwe bepalingen ter vervanging van de nietige c.q. vernietigde bepalingen overeen te komen. Hierbij wordt zoveel mogelijk het doel en de strekking van de oorspronkelijke bepaling in acht genomen.' ) . "\n"
				. react2u_inhoud_p( 'React2u is gerechtigd om deze algemene voorwaarden eenzijdig te wijzigen. React2u publiceert haar actuele algemene voorwaarden op de website.' ) . "\n"
				. react2u_inhoud_p( 'De rechtsverhouding tussen opdrachtgever en React2u is een overeenkomst van opdracht. React2u heeft daarbij een inspanningsverplichting.' ) . "\n"
				. react2u_inhoud_p( 'Door het aanmaken van een account is opdrachtgever aangesloten bij een arbodienst. Het basiscontract is te downloaden via de website. De algemene voorwaarden maken een onverbrekelijk deel uit van het basiscontract.' ) . "\n"
				. react2u_inhoud_p( 'React2u offreert verrichtingen via mail. De opdracht komt tot stand zodra opdrachtgever akkoord heeft gegeven via mail of wanneer opdrachtgever een verrichting heeft aangekruist bij de ziekmelding, waarbij de actuele prijs is genoemd.' ) . "\n"
				. react2u_inhoud_p( 'Zowel opdrachtgever als React2u kunnen de overeenkomst te allen tijde onmiddellijk of tussentijds opzeggen.' ) . "\n"
				. react2u_inhoud_p( 'Op de rechtsverhouding zijn de artikelen 7:404 en 7:407 lid 2 van het Burgerlijk Wetboek uitdrukkelijk niet van toepassing.' ) . "\n"
				. react2u_inhoud_h2( 'B. Aanbiedingen en offertes' ) . "\n"
				. react2u_inhoud_p( 'Offertes van React2u zijn geldig gedurende 14 dagen tenzij in de offerte uitdrukkelijk een andere aanvaardingstermijn is opgenomen. Een overeenkomst komt tot stand na rechtsgeldige ondertekening door beide partijen van een overeenkomst of middels een voorstel van React2u via mail, waarop opdrachtgever via mail akkoord geeft.' ) . "\n"
				. react2u_inhoud_p( 'De prijzen in de genoemde aanbiedingen en offertes zijn exclusief BTW en andere heffingen van overheidswege, alsmede eventuele in het kader van de overeenkomst te maken kosten, waaronder casemanagement-, organisatie-, secretariaat-, reis-, verblijf-, verzend- en administratiekosten.' ) . "\n"
				. react2u_inhoud_p( 'Indien na het moment van aanbieding of na het tot stand komen van de overeenkomst belastingen, heffingen of andere lasten van overheidswege worden ingevoerd of verhoogd, worden deze aan de opdrachtgever doorberekend.' ) . "\n"
				. react2u_inhoud_p( 'Wijzigingen dienen tussen React2u en de wederpartij te worden overeengekomen. Indien geen overeenstemming kan worden bereikt, dan is React2u gerechtigd om de overeenkomst tussentijds te beëindigen tenzij zulks in strijd zou zijn met de redelijkheid en billijkheid.' ) . "\n"
				. react2u_inhoud_p( 'Afspraken die geen betrekking hebben op een individuele werknemer dienen uiterlijk zeven werkdagen voor het afgesproken tijdstip te worden geannuleerd. Annulering van afspraken betreffende individuele werknemers dient (ongeacht de datum van herstelmelding) uiterlijk vijf werkdagen voor het afgesproken tijdstip te geschieden door opdrachtgever. Het niet reageren of het niet verschijnen van de werknemer komt in ieder geval voor risico van de opdrachtgever.' ) . "\n"
				. react2u_inhoud_h2( 'C. Rechten en verplichtingen React2u' ) . "\n"
				. react2u_inhoud_p( 'React2u zal de te verrichten diensten en werkzaamheden naar beste inzicht, kunnen en vermogen en overeenkomstig de eisen van goed vakmanschap uitvoeren.' ) . "\n"
				. react2u_inhoud_p( 'React2u is gerechtigd bij de uitvoering van haar werkzaamheden derden in te schakelen. Tenzij de opdrachtgever met de ingeschakelde derde een nieuwe overeenkomst aangaat, blijven deze algemene voorwaarden onverminderd van kracht.' ) . "\n"
				. react2u_inhoud_p( 'Elke werknemer heeft het recht een bedrijfsarts te bezoeken. Indien een werknemer zonder overleg met zijn werkgever de bedrijfsarts wenst te bezoeken, zal React2u een afspraak met deze werknemer inplannen zonder hiervoor voorafgaand offerte te doen. Hiervoor gelden de gebruikelijke tarieven.' ) . "\n"
				. react2u_inhoud_p( 'Elke werknemer die twijfelt over het oordeel van een bedrijfsarts kan om een second opinion van een andere bedrijfsarts vragen. React2u kan zo’n afspraak, ook zonder toestemming van opdrachtgever inplannen. Opdrachtgever dient de kosten van een dergelijke second opinion ook zonder offerte en een akkoord te voldoen. Hiervoor gelden de gebruikelijke tarieven.' ) . "\n"
				. react2u_inhoud_p( 'Indien naar het oordeel van React2u extra werkzaamheden noodzakelijk zijn, waaronder begrepen doch niet beperkt tot het inwinnen van medische informatie of inschakelen van experts, voor de uitvoering van de opdracht dan kan React2u deze extra werkzaamheden uitvoeren of doen uitvoeren. Voorts informeert React2u onverwijld opdrachtgever over de aard en de vergoeding van deze extra werkzaamheden.' ) . "\n"
				. react2u_inhoud_p( 'De bedrijfsarts is verplicht melding te maken van beroepsziekten en beroep gebonden aandoeningen bij het Nederlands Centrum voor Beroepsziekten (NCvB). Opdrachtgever verstrekt informatie en betrekt React2u bij het voorkomen, signaleren en -waar mogelijk- behandelen van beroepsziekten en beroepsgebonden aandoeningen om deze te vertalen naar een preventieve aanpak.' ) . "\n"
				. react2u_inhoud_p( 'React2u is gerechtigd werknemers die de normale omgangs- en fatsoensnormen niet in acht nemen, middels gemotiveerde kennisgeving aan de opdrachtgever, met onmiddellijke ingang en zonder ingebrekestelling, uit te sluiten van dienstverlening, zonder dat deze uitsluiting aanleiding geeft tot aanpassing van de door de opdrachtgever aan React2u verschuldigde vergoeding. React2u aanvaardt geen enkele aansprakelijkheid voor eventuele schade, die ten gevolge van de uitsluiting voor de opdrachtgever dan wel voor de werknemer ontstaat.' ) . "\n"
				. react2u_inhoud_p( 'In geval wijzigingen in wetgeving en/of door de overheid anderszins opgelegde regelgeving een aanpassing van de dienstverlening tot gevolg zullen hebben, dan zullen partijen de overeenkomst in goed onderling overleg dientengevolge (zo nodig met terugwerkende kracht tot de datum waarop de wijzigingen van kracht worden) wijzigen. In een dergelijke situatie is React2u gerechtigd de eventuele direct of indirect uit de opgelegde wijzigingen voortvloeiende extra kosten in rekening te brengen bij opdrachtgever.' ) . "\n"
				. react2u_inhoud_h2( 'D. Verplichtingen opdrachtgever' ) . "\n"
				. react2u_inhoud_p( 'Opdrachtgever is verantwoordelijk voor het tijdig en op de juiste wijze aanleveren aan React2u van de gegevens die React2u nodig heeft om de overeenkomst te kunnen uitvoeren. Alleen wanneer een werknemer ziek wordt gemeld in het systeem van React2u is React2u in staat een goed advies te geven voor het begeleiden van het verzuim. Opdrachtgever zal ook alle redelijke aanwijzingen van React2u opvolgen mede in het kader van de Wet Verbetering Poortwachter.' ) . "\n"
				. react2u_inhoud_p( 'Indien deze gegevens niet tijdig zijn verstrekt, dan wel de instructies niet zijn opgevolgd of de noodzakelijke medewerking van (medewerkers van) opdrachtgever niet wordt verleend, treden partijen in overleg. Nadat is gebleken dat dit niet tot resultaat heeft geleid, heeft React2u het recht de uitvoering van een overeenkomst op te schorten en/of uit de vertraging voortvloeiende (extra) kosten volgens de gebruikelijke tarieven in rekening te brengen.' ) . "\n"
				. react2u_inhoud_p( 'De opdrachtgever is verantwoordelijk voor alle noodzakelijke informatieverstrekking aan werknemers, alsmede voor het opleggen van alle noodzakelijke verplichtingen aan werknemers.' ) . "\n"
				. react2u_inhoud_p( 'Opdrachtgever informeert de preventiemedewerker, de OR/personeelsvertegenwoordiging en vraagt zo nodig instemming.' ) . "\n"
				. react2u_inhoud_p( 'Opdrachtgever wijst haar werknemers op het recht een bedrijfsarts te spreken en op het recht op een second opinion bij een andere bedrijfsarts, wanneer zij twijfelen over het oordeel van de bedrijfsarts.' ) . "\n"
				. react2u_inhoud_p( 'Opdrachtgever betrekt React2u bij het bedrijfsbeleid voor gezond en veilig werken voor overleg met de OR of personeelsvertegenwoordiging, betrokken medewerkers of preventiemedewerker en stelt React2u in staat goed inzicht te krijgen in het preventie-, verzuim- en re-integratiebeleid en de arbeidsomstandigheden door inspectie en onderzoek ter plaatse en door het voeren van gesprekken met werknemers. Opdrachtgever stelt alle relevante informatie beschikbaar aan React2u. Op basis daarvan wordt gezamenlijk invulling gegeven aan een preventieve bedrijfsgezondheidszorg.' ) . "\n"
				. react2u_inhoud_p( 'Indien de overeengekomen diensten in het bedrijf van de opdrachtgever plaatsvinden, zal de opdrachtgever, indien React2u daar tijdig om verzoekt kosteloos personeel, materiaal en werkruimte ter beschikking stellen.' ) . "\n"
				. react2u_inhoud_h2( 'E. Tarieven en betaling' ) . "\n"
				. react2u_inhoud_p( 'React2u zal voor de door haar te verrichten werkzaamheden aan opdrachtgever de tarieven in rekening brengen conform het door React2u vast te stellen tarievenoverzicht, tenzij in de overeenkomst uitdrukkelijk een andere prijsafspraak is vastgelegd. React2u behoudt zich het recht voor het tarievenoverzicht eenzijdig te wijzigen.' ) . "\n"
				. react2u_inhoud_p( 'Kosten in verband met het vragen van inlichtingen, waaronder begrepen, maar niet limitatief opgesomd, het vragen van inlichtingen bij de curatieve sector en het opvragen van medische dossiers bij de (voormalige) arbodienst, alsmede kosten verbonden aan door React2u op grond van(wettelijke) regelingen in te schakelen derden, komen, ook indien hierover geen voorafgaand overleg met de opdrachtgever heeft plaatsgevonden, voor rekening van de opdrachtgever.' ) . "\n"
				. react2u_inhoud_p( 'Betaling dient te geschieden binnen 14 dagen na factuurdatum en op een door React2u aan te geven rekeningnummer, tenzij anders wordt overeengekomen c.q. anders op de factuur vermeld staat. Bij overschrijding van deze termijn is de opdrachtgever van rechtswege in verzuim en is een vertragingsrente verschuldigd van 1% per maand, tenzij de wettelijke rente hoger is, in welk geval de wettelijke rente geldt. De rente over het opeisbare bedrag zal worden berekend vanaf het moment dat opdrachtgever in verzuim is tot het moment van voldoening van het volledige bedrag, waarbij een gedeelte van een maand te gelden heeft als een hele maand.' ) . "\n"
				. react2u_inhoud_p( 'Opdrachtgever is vanaf het moment dat hij in verzuim verkeert 15% van het onbetaald gelaten bedrag verschuldigd aan buitengerechtelijke kosten, zulks met een minimum van € 40,-.' ) . "\n"
				. react2u_inhoud_p( 'Alle kosten ter verdere verkrijging van voldoening in rechte komen volledig, derhalve inclusief kosten van advocaat of gemachtigde, voor rekening van opdrachtgever.' ) . "\n"
				. react2u_inhoud_p( 'Indien (volledige) betaling achterwege blijft, is React2u gerechtigd eventuele nog lopende opdrachten op te schorten dan wel een overeenkomst op te zeggen. Opschorting van de overeengekomen diensten laat de verplichting voor de opdrachtgever de openstaande facturen te voldoen onverlet.' ) . "\n"
				. react2u_inhoud_p( 'Klachten over in rekening gebrachte bedragen dienen zo spoedig mogelijk, doch uiterlijk binnen 14 dagen na factuurdatum, schriftelijk door de opdrachtgever te zijn ingediend, bij gebreke waarvan de opdrachtgever geacht wordt akkoord te zijn met de in rekening gebrachte bedragen. Reclames geven geen recht op verrekening, of op opschorting van de betaling.' ) . "\n"
				. react2u_inhoud_p( 'In het geval van faillissement of als er surseance van betaling van de opdrachtgever wordt aangevraagd, dan wel dat er ten laste van de opdrachtgever beslag wordt gelegd, zijn de vorderingen van React2u onmiddellijk opeisbaar.' ) . "\n"
				. react2u_inhoud_p( 'Wanneer React2u tijdens de duur van de aan haar verstrekte opdracht aanwijzingen ontvangt omtrent onvoldoende kredietwaardigheid van de opdrachtgever, dan heeft React2u het recht de opdracht terug te geven, onverminderd de verplichting van de opdrachtgever tot betaling voor reeds verrichte werkzaamheden. Dit tenzij de opdrachtgever zorg draagt voor vooruitbetaling.' ) . "\n"
				. react2u_inhoud_p( 'React2u is gerechtigd diensten vooraf in rekening te brengen en de uitvoer daarvan uit te stellen totdat opdrachtgever de factuur volledig heeft voldaan.' ) . "\n"
				. react2u_inhoud_p( 'De door opdrachtgever gedane betalingen strekken eerst in mindering op de kosten, vervolgens in mindering van de opengevallen rente en tenslotte in mindering van de hoofdsom en de lopende rente. React2u kan, zonder daardoor in verzuim te komen, een aanbod tot betaling weigeren, indien de opdrachtgever een andere volgorde voor de toerekening aanwijst. React2u kan volledige aflossing van de hoofdsom weigeren, indien daarbij niet eveneens de opengevallen en lopende rente alsmede de kosten worden voldaan.' ) . "\n"
				. react2u_inhoud_p( 'Indien door omstandigheden toerekenbaar aan opdrachtgever geplande werkzaamheden niet door React2u kunnen worden verricht, is opdrachtgever de overeengekomen vergoeding en daaraan verbonden kosten aan React2u verschuldigd. De overeengekomen vergoeding is evenwel niet verschuldigd bij schriftelijke en incidentele annulering van:' ) . "\n"
				. react2u_inhoud_p( 'a) cursussen en trainingen tot twee maanden voor aanvang (opdrachtgever heeft voorts binnen zijn' ) . "\n"
				. react2u_inhoud_p( 'organisatie het recht van substitutie);' ) . "\n"
				. react2u_inhoud_p( 'b) projecten tot twee maanden voor aanvang;' ) . "\n"
				. react2u_inhoud_p( 'c) individuele werknemer georiënteerde opdrachten tot vijf dagen voor aanvang;' ) . "\n"
				. react2u_inhoud_p( 'De overeengekomen diensten worden tegen een vaste prijs of op uurbasis aan opdrachtgever gefactureerd. In geval van opdrachten begroot tot € 500,- (ex BTW) wordt het bedrag achteraf in rekening gebracht. In geval van opdrachten vanaf €500,- is opdrachtgever 50% van de vaste prijs bij vooruitbetaling verschuldigd en 50% na afloop van het project.' ) . "\n"
				. react2u_inhoud_p( 'Indien medische dossiers dienen te worden overgedragen aan een derde, dan is React2u gerechtigd om de daarmee verband houdende redelijke kosten bij opdrachtgever in rekening te brengen.' ) . "\n"
				. react2u_inhoud_p( 'Door React2u aangeboden en overeengekomen van tijd tot tijd vastgestelde tarieven en kosten luiden steeds in Euro en zijn exclusief omzetbelasting (BTW) en andere heffingen welke van overheidswege specifiek voor de werkzaamheden, samenhangend met de dienstverlening, worden opgelegd.' ) . "\n"
				. react2u_inhoud_h2( 'F. Aansprakelijkheid' ) . "\n"
				. react2u_inhoud_p( 'React2u zal alle met haar overeengekomen werkzaamheden zorgvuldig verrichten met inachtneming van de specifieke deskundigheid, die van haar in de gegeven omstandigheden verwacht mag worden. Ondanks wederzijdse inspanning van partijen kan React2u echter nooit garanderen dat een door de opdrachtgever gewenst en/of door React2u verwacht resultaat bereikt zal worden. React2u is daarvoor dan ook niet aansprakelijk.' ) . "\n"
				. react2u_inhoud_p( 'React2u sluit aansprakelijkheid van elke vorm van schade veroorzaakt door of op advies van ingeschakelde derden volledig uit.' ) . "\n"
				. react2u_inhoud_p( 'React2u is niet aansprakelijk voor opgelegde sancties door derden (veelal Uitvoeringsinstellingen), zoals een loondoorbetalingsverplichting in het derde ziektejaar, re-integratiekosten, (gevolgen van) afwijzing/toewijzing WIA, etc.' ) . "\n"
				. react2u_inhoud_p( 'Verzuimteam sluit aansprakelijkheid voor bedrijfsschade, gevolgschade of andere indirecte schade, waaronder begrepen schade wegens gederfde winst, gemiste besparingen, schade door bedrijfsstagnatie, loondoorbetaling bij ziekte, verlies van gegevens of premieverhogingen van publieke en/of private verzekeringen uit.' ) . "\n"
				. react2u_inhoud_p( 'De aansprakelijkheid van React2u voor directe schade wegens toerekenbare tekortkoming in de nakoming van een overeenkomst of wegens onrechtmatige daad is beperkt tot het bedrag dat de opdrachtgever, voor de betreffende dienstverlening in rekening is gebracht. Indien om welke reden dan ook geen uitkering krachtens de beroepsaansprakelijkheidsverzekering plaatsvindt, is iedere aansprakelijkheid van React2u beperkt tot een bedrag van €500,- inclusief BTW.' ) . "\n"
				. react2u_inhoud_p( 'Onder directe schade wordt uitsluitend verstaan:' ) . "\n"
				. react2u_inhoud_p( '– de redelijke kosten ter vaststelling van de oorzaak en de omvang van de schade, voor zover de' ) . "\n"
				. react2u_inhoud_p( 'vaststelling betrekking heeft op schade in de zin van deze voorwaarden;' ) . "\n"
				. react2u_inhoud_p( '– de eventuele redelijke kosten gemaakt om de gebrekkige prestatie van React2u aan de' ) . "\n"
				. react2u_inhoud_p( 'overeenkomst te laten beantwoorden, tenzij deze niet aan React2u toegerekend kunnen worden;' ) . "\n"
				. react2u_inhoud_p( '– redelijke kosten, gemaakt ter voorkoming of beperking van schade, voor zover opdrachtgever aantoont dat deze kosten hebben geleid tot beperking van directe schade als bedoeld in deze algemene voorwaarden.' ) . "\n"
				. react2u_inhoud_p( 'De opdrachtgever is te allen tijde gehouden om schadebeperkend te handelen.' ) . "\n"
				. react2u_inhoud_p( 'Onverminderd het bepaalde in artikel 6:89 van het Burgerlijk Wetboek vervalt het recht op schadevergoeding in ieder geval twaalf maanden na de gebeurtenis waaruit schade direct of indirect voortvloeit en waarvoor React2u aansprakelijk mocht zijn.' ) . "\n"
				. react2u_inhoud_p( 'React2u is niet aansprakelijk voor enige schade die (mede) het gevolg is van het niet (juist, tijdig of volledig) nakomen door de opdrachtgever van verplichtingen rustend op de opdrachtgever op grond van een overeenkomst en als opgenomen in de werkafspraken, op grond van deze algemene voorwaarden of op grond van de toepasselijke wet- en regelgeving. Onder deze verplichtingen vallen in ieder geval, doch niet uitsluitend, het op juist wijze verstrekken van alle relevante informatie aan React2u en het naleven van door React2u gestelde, dan wel wettelijke termijnen.' ) . "\n"
				. react2u_inhoud_p( 'In geval van mondelinge/telefonische communicatie tussen partijen is React2u niet aansprakelijk voor schade voortvloeiend uit misverstanden of uit onjuist overgekomen informatie.' ) . "\n"
				. react2u_inhoud_p( 'React2u is niet aansprakelijk voor schade die (mede) veroorzaakt is door het niet (juist, tijdig, of volledig) opvolgen van instructies en adviezen van React2u of van derden door de opdrachtgever.' ) . "\n"
				. react2u_inhoud_p( 'React2u maakt gebruik van zelfstandig werkende professionals. React2u aanvaardt geen enkele aansprakelijkheid voor ingeschakelde derden, noch wanneer deze zijn ingeschakeld door React2u, noch wanneer deze door opdrachtgever zelf zijn ingeschakeld, noch wanneer deze door anderen zijn ingeschakeld. Ook niet wanneer de dienstverlening van de derde in rekening is gebracht bij opdrachtgever door React2u.' ) . "\n"
				. react2u_inhoud_h2( 'G. Privacy, vertrouwelijkheid en geheimhouding' ) . "\n"
				. react2u_inhoud_p( 'Partijen zijn verplicht elkaar over en weer alle redelijke medewerking te verlenen teneinde de andere partij in staat te stellen haar verplichtingen op grond van de toepasselijke privacywetgeving na te komen.' ) . "\n"
				. react2u_inhoud_p( 'Partijen zullen alle informatie, knowhow, (patiënt-)gegevens of specificaties die verband houden met de uitvoering van deze overeenkomst en/of de onderneming van de andere partij, vertrouwelijk behandelen en zullen deze niet aan derden kenbaar maken, tenzij de partij van wie de informatie afkomstig is daartoe schriftelijk toestemming heeft gegeven. Hetzelfde geldt ten aanzien van de inhoud van de overeenkomst.' ) . "\n"
				. react2u_inhoud_p( 'Deze geheimhoudingsverplichting geldt niet ten aanzien van informatie die publiekelijk bekend is geworden zonder dat er sprake is van een overtreding van een geheimhoudingsbeding, of indien informatie bij de ontvanger van de informatie al bekend was ten tijde van de ontvangst van de informatie krachtens de overeenkomst, of als die informatie door een derde is verstrekt, zonder dat die derde daarmee een geheimhoudingsbeding heeft overtreden. Voorts geldt de geheimhoudingsverplichting niet voor zover openbaarmaking verplicht is op grond van de wet, of een bindende uitspraak van de rechter, een ander overheidsorgaan of een beroepsplicht. Voor zover mogelijk zal de openbaar makende partij echter voor de openbaarmaking met de andere partij overleggen over de vorm en de inhoud van de openbaarmaking.' ) . "\n"
				. react2u_inhoud_p( 'Partijen zullen de geheimhoudingsverplichting ook opleggen aan hun werknemers en alle andere derden, die voor hen zullen werken.' ) . "\n"
				. react2u_inhoud_p( 'Opdrachtgever geeft toestemming aan React2u om via e-mail met hem en derden te communiceren. Opdrachtgever is zich bewust dat de vertrouwelijkheid van per e-mail verzonden informatie niet gewaarborgd is.' ) . "\n"
				. react2u_inhoud_p( 'Indien medische gegevens dienen te worden overgedragen, dan is hieraan voorafgaand persoonlijke en schriftelijke toestemming van de betrokken werknemer vereist. React2u is gerechtigd aan de opdrachtgever de hiermee verband houdende kosten in rekening te brengen. Na de overdracht van de dossiers vervalt iedere aansprakelijkheid van React2u ter zake. React2u is niet aansprakelijk voor schending van de privacy gegevens na overdracht van de medische gegevens aan derden. React2u is gerechtigd pas aan overdracht van dossiers mee te weken, nadat alle door de opdrachtgever aan React2u verschuldigde bedragen, inclusief de kosten die verband houden met de overdracht, zijn voldaan.' ) . "\n"
				. react2u_inhoud_p( 'React2u zal de opdrachtgever niet mededelen welke werknemers gebruik hebben gemaakt van een arbeidsomstandigheden spreekuur of zich hebben onderworpen aan een Periodiek Arbeidsgezondheidskundig Onderzoek, noch mededelingen doen dienaangaande die herleidbaar zouden kunnen zijn tot individuele werknemers. React2u zal slechts in algemene zin de aard van de problemen, die in dit spreekuur aan de orde of uit het onderzoek naar voren zijn gekomen, met de opdrachtgever bespreken. React2u staat hierbij in voor de volledige anonimiteit van de betrokken individuele werknemer(s).' ) . "\n"
				. react2u_inhoud_p( 'In geval van een aanstellingskeuring bepaalt de te onderzoeken persoon of hij de uitslag van de keuring (als eerste) wenst te vernemen en of er mededelingen aan de opdrachtgever mogen worden gedaan met betrekking tot de uitslag van de keuring. De opdrachtgever is React2u de kosten van de aanstellingskeuring verschuldigd, ongeacht of de opdrachtgever de uitslag van de keuring al dan niet verneemt.' ) . "\n"
				. react2u_inhoud_h2( 'H. Vrijwaringen' ) . "\n"
				. react2u_inhoud_p( 'De opdrachtgever vrijwaart React2u tegen alle aanspraken van derden, de kosten van juridische bijstand daaronder begrepen, die op enige wijze samenhangen met de werkzaamheden voor de opdrachtgever verricht, tenzij een en ander een gevolg is van grove nalatigheid of opzettelijke misdraging(en) zijdens React2u.' ) . "\n"
				. react2u_inhoud_p( 'Indien opdrachtgever aan React2u informatiedragers, elektronische bestanden of software etc. verstrekt, garandeert de opdrachtgever dat de informatiedragers, elektronische bestanden of software vrij zijn van virussen en defecten.' ) . "\n"
				. react2u_inhoud_h2( 'I. Overmacht' ) . "\n"
				. react2u_inhoud_p( 'Indien één van de partijen niet aan haar verplichtingen kan voldoen, of zij redelijkerwijs kan verwachten hieraan niet te kunnen gaan voldoen, hetzij als gevolg van overmacht, hetzij als gevolg van andere omstandigheden, is deze partij gehouden de andere partij daarvan onmiddellijk schriftelijk op de hoogte te stellen.' ) . "\n"
				. react2u_inhoud_p( 'React2u is niet aansprakelijk voor het niet, niet tijdig of niet volledig nakomen van haar verplichtingen indien er sprake is van overmacht. Alle omstandigheden die de naleving van een overeenkomst belemmeren en die in redelijkheid niet voor risico van React2u behoren te komen, worden beschouwd als niet-toerekenbare tekortkoming en leveren overmacht op.' ) . "\n"
				. react2u_inhoud_p( 'Partijen zijn niet gehouden tot het nakomen van enige verplichting, indien zij daartoe gehinderd worden als gevolg van een omstandigheid die niet is te wijten aan schuld, en noch krachtens de wet, een rechtshandeling of in het verkeer geldende opvattingen voor hun rekening komt. Omstandigheden waardoor partijen zich op overmacht kunnen beroepen, doen zich onder meer, en derhalve niet uitsluitend, voor in geval van oorlog, oorlogsgevaar en oproer, terroristische aanslagen of dreigingen, natuurrampen, belemmerende maatregelen van binnenlandse en buitenlandse overheden, sabotage, (algehele) werkstaking, bedrijfsbezetting, vervoerstremmingen, tekortkomingen van leveranciers van goederen en/of diensten, computer of elektronicastoringen, bedrijfsstoring zoals brand, het verloren gaan van gegevens, stroomuitval, bedrijfsongeval, epidemieën ten gevolge waarvan de uitvoering van een overeenkomst tijdelijk of blijvend onmogelijk is.' ) . "\n"
				. react2u_inhoud_p( 'Onder overmacht wordt in deze algemene voorwaarden – naast hetgeen daaromtrent in de wet en jurisprudentie wordt begrepen – verstaan, alle van buiten komende oorzaken, voorzien of niet-voorzien, waarop React2u geen invloed kan uitoefenen, doch waardoor React2u niet in staat is de verplichtingen na te komen. Werkstakingen in het bedrijf van React2u worden daaronder begrepen.' ) . "\n"
				. react2u_inhoud_p( 'React2u heeft ook het recht zich op overmacht te beroepen, indien de omstandigheid die (verdere) nakoming verhindert, intreedt nadat React2u haar verplichtingen had moeten nakomen.' ) . "\n"
				. react2u_inhoud_p( 'Partijen kunnen gedurende de periode dat de overmacht voortduurt de verplichtingen uit de overeenkomst opschorten. Indien deze periode langer duurt dan twee maanden, is ieder der partijen gerechtigd de overeenkomst te ontbinden, zonder verplichting tot vergoeding van enige schade aan de andere partij.' ) . "\n"
				. react2u_inhoud_p( 'Voor zover React2u ten tijde van het intreden van overmacht inmiddels gedeeltelijk zijn verplichtingen uit de overeenkomst is nagekomen of deze zal kunnen nakomen en aan het nagekomen respectievelijk na te komen gedeelte zelfstandige waarde toekomt, is React2u gerechtigd om het reeds nagekomen respectievelijk na te komen gedeelte in rekening te brengen. Opdrachtgever is gehouden deze declaratie te voldoen als ware het een afzonderlijke overeenkomst.' ) . "\n"
				. react2u_inhoud_h2( 'J. Geschillen' ) . "\n"
				. react2u_inhoud_p( 'React2u voert de opdrachten naar beste vermogen uit. Klachten over de kwaliteit van de verrichte werkzaamheden dienen door de opdrachtgever binnen 8 dagen na ontdekking, doch uiterlijk binnen 14 dagen na voltooiing van de betreffende werkzaamheden, schriftelijk te worden gemeld aan React2u. De klacht dient een zo gedetailleerd mogelijke omschrijving van de tekortkoming te bevatten, zodat React2u in staat is adequaat te reageren.' ) . "\n"
				. react2u_inhoud_p( 'Als een klacht gegrond is, dan dient de opdrachtgever React2u in de gelegenheid te stellen om alsnog binnen een redelijke termijn aan haar verplichtingen te voldoen.' ) . "\n"
				. react2u_inhoud_p( 'Indien door of naar aanleiding van de opdracht een geschil rijst tussen de opdrachtgever en de React2u, dan zullen partijen trachten dit geschil eerst door minnelijk overleg op te lossen.' ) . "\n"
				. react2u_inhoud_p( 'Komen partijen er niet uit dan wordt de klacht voorgelegd aan een onafhankelijk professional (mediator / advocaat) die bemiddelt tussen partijen.' ) . "\n"
				. react2u_inhoud_p( 'Op elke overeenkomst tussen React2u en de opdrachtgever is het Nederlands recht van toepassing en heeft de Nederlandse rechter rechtsmacht.' ) . "\n"
				. react2u_inhoud_p( 'De rechter in de vestigingsplaats van React2u is bij uitsluiting bevoegd van geschillen kennis te nemen. Niettemin heeft React2u het recht het geschil voor te leggen aan de volgens de wet bevoegde rechter.' ) . "\n",
		),
		'klachtenprocedure'    => array(
			'titel'   => 'Klachtenprocedure',
			'excerpt' => 'React2u neemt klachten serieus. Zo meld je een klacht, en zo handelen we hem af.',
			'body'    =>
			react2u_inhoud_p( 'React2u voelt zich verantwoordelijk voor de wijze waarop u onze dienstverlening ervaart. Wij nemen klachten dan ook uiterst serieus en willen samen met u op zoek naar de best mogelijke oplossingen. Om te komen tot een goede klachtafhandeling heeft React2u onderstaande klachtenprocedure opgesteld.' ) . "\n"
			. react2u_inhoud_h2( 'Klacht aanmelden' ) . "\n"
			. react2u_inhoud_p( 'U meldt uw klacht schriftelijk bij ons, dit mag per mail of per post. Daarna ontvangt u vanuit React2u binnen 3 werkdagen een ontvangstbevestiging. Ons uitgangspunt is om uw klacht binnen 14 dagen af te handelen.' ) . "\n"
			. react2u_inhoud_p( 'Mocht u iemand anders willen machtigen om uw klacht in te dienen dan ontvangen wij graag een ondertekende machtiging van de persoon die daadwerkelijk de klacht wil indienen.' ) . "\n"
			. react2u_inhoud_h2( 'Behandeling van de klacht' ) . "\n"
			. react2u_inhoud_p( 'De klacht wordt in behandeling genomen door de directie of door de directie aangewezen persoon. Betrokken partijen worden persoonlijk benaderd om tot verduidelijking van de klacht te komen. Indien een betrokkene het prettig vindt om iemand mee te nemen in het gesprek is dit mogelijk als dit vooraf kenbaar is gemaakt bij React2u.' ) . "\n"
			. react2u_inhoud_h2( 'Afhandeling van de klacht' ) . "\n"
			. react2u_inhoud_p( 'Op basis van de verzamelde informatie wordt bij voorkeur in samenspraak met betrokken partijen een uitspraak gedaan. Deze uitspraak wordt ook door React2u schriftelijk vastgelegd. Indien een klacht (deels) gegrond is dan gebruikt React2u dit als verbeteractie om de kwaliteit van de dienstverlening te verbeteren.' ) . "\n"
			. react2u_inhoud_h2( 'Ontevreden over de klachtafhandeling' ) . "\n"
			. react2u_inhoud_p( 'Indien u ontevreden bent over de afhandeling van uw klacht dan verzoekt React2u dit schriftelijk kenbaar te maken met daarin opgenomen de reden van uw ontevredenheid. De heer J. Vissering (DGA) zal dan een reactie geven op uw schrijven.' ) . "\n"
			. react2u_inhoud_h2( 'Uitgezonderd' ) . "\n"
			. react2u_inhoud_p( 'De klacht is niet ontvankelijk als u onvrede heeft over een advies van de bedrijfsarts en/of een andere ingeschakelde deskundige. Hiervoor kunt u een deskundigenoordeel bij het UWV aanvragen.' ),
		),
	);
}
